apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: kubevirt-hyperconverged
  annotations:
    kubevirt.kubevirt.io/jsonpatch: |-
      [
        {
          "op": "add",
          "path": "/spec/configuration/developerConfiguration/featureGates",
          "value": ["ConfigurableHypervisor", "CPUManager", "Snapshot", "HotplugVolumes", "ExpandDisks", "HostDevices", "VMExport", "KubevirtSeccompProfile", "VMPersistentState", "InstancetypeReferencePolicy", "WithHostModelCPU", "HypervStrictCheck"]
        },
        {
          "op": "add",
          "path": "/spec/configuration/hypervisorConfiguration",
          "value": { "name": "hyperv-layered" }
        },
        {
          "op": "add",
          "path": "/spec/configuration/evictionStrategy",
          "value": "None"
        },
        {
          "op": "replace",
          "path": "/spec/configuration/obsoleteCPUModels/qemu64",
          "value": false
        },
        {
          "op": "replace",
          "path": "/spec/configuration/obsoleteCPUModels/qemu64-v1",
          "value": false
        },
        {
          "op": "add",
          "path": "/spec/configuration/cpuModel",
          "value": "qemu64-v1"
        }
      ]
spec:
  permittedHostDevices:
    pciHostDevices:
    - pciDeviceSelector: "10DE:2330"
      resourceName: "nvidia.com/GH100"  